# Generated by Django 5.0.1 on 2024-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=400)),
                ('data_time', models.DateTimeField()),
                ('link_to', models.CharField(max_length=300)),
            ],
        ),
    ]
