# Generated by Django 5.0.1 on 2024-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_tools',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
